apiVersion: batch/v1
kind: Job
metadata:
  name: redis-benchmark-write
  namespace: redis-sentinel
spec:
  # 4 pods for writes
  parallelism: 4
  completions: 4
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: redis-benchmark-write
        tier: write
    spec:
      restartPolicy: Never
      containers:
      - name: memtier-write
        image: redislabs/memtier_benchmark:latest
        command:
        - sh
        - -c
        - |
          echo "====================================="
          echo "WRITE Benchmark (Data Population)"
          echo "====================================="
          echo "Pod: $HOSTNAME"
          echo "Target: redis-ha.redis-sentinel.svc.cluster.local:6379 (Master)"
          echo "Operation: 100% SET (data population)"
          echo ""
          
          # Wait for HAProxy
          echo "Waiting for HAProxy..."
          sleep 5
          
          # Run memtier_benchmark - WRITE ONLY
          memtier_benchmark \
            --server=redis-ha.redis-sentinel.svc.cluster.local \
            --port=6379 \
            --protocol=redis \
            --clients=10 \
            --threads=2 \
            --test-time=120 \
            --ratio=1:0 \
            --data-size=256 \
            --key-minimum=1 \
            --key-maximum=100000 \
            --key-pattern=P:P \
            --randomize \
            --distinct-client-seed \
            --print-percentiles=50,90,95,99,99.9
          
          echo ""
          echo "Write benchmark completed!"
          echo "Data populated: 100K keys on master"
          
        resources:
          requests:
            cpu: 500m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 512Mi
