apiVersion: v1
kind: Service
metadata:
  name: redis-ha
  namespace: redis-sentinel
  labels:
    app: haproxy
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  - port: 8404
    targetPort: 8404
    protocol: TCP
    name: stats
  selector:
    app: haproxy
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-stats
  namespace: redis-sentinel
  labels:
    app: haproxy
spec:
  type: ClusterIP
  ports:
  - port: 8404
    targetPort: 8404
    protocol: TCP
    name: stats
  selector:
    app: haproxy
